after_success:
- coveralls
before_install:
- pip install coveralls
- if [ -z "$_COMMAND" ]; then export _COMMAND=test; fi
- if [ -z "$_DJANGO" ]; then export _DJANGO=1.10.4; fi
env:
- !!python/unicode '_DJANGO=1.10.4 _DJANGO_STORAGES=1.5.1 _BOTO=2.45.0'
- !!python/unicode '_DJANGO=1.8.17 _DJANGO_STORAGES=1.5.1 _BOTO=2.45.0'
- !!python/unicode '_DJANGO=1.9.12 _DJANGO_STORAGES=1.5.1 _BOTO=2.45.0'
install:
- pip install Django==$_DJANGO boto==$_BOTO django-storages==$_DJANGO_STORAGES
- pip install coverage django-nose
- pip install https://github.com/PyCQA/astroid/zipball/master https://github.com/PyCQA/pylint/zipball/master
language: python
matrix:
  include:
  - env: _COMMAND=pylint
    python: 3.5

notifications:
  email:
    on_failure: change
    on_success: change
python:
- 2.7
- 3.5
script: make $_COMMAND
